# apiVersion: v1
# kind: Pod
# metadata:
#   name: ubuntu-sleeper
# spec:
#   securityContext:
#     runAsUser: 1010
#   containers:
#     - name: ubuntu
#       image: ubuntu
#       command: ["sleep", "infinity"]


# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: ubuntu-sleeper
#   namespace: default
# spec:
#   securityContext:
#     runAsUser: 1010
#   containers:
#   - command:
#     - sleep
#     - "4800"
#     image: ubuntu
#     name: ubuntu-sleeper



apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  securityContext:
    runAsUser: 0
    capabilities:
      add: ["SYS_TIME"]
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu


---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu-sleeper
    securityContext:
      capabilities:
        add: ["SYS_TIME"]

---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu-sleeper
    securityContext:
      capabilities:
        add: ["SYS_TIME", "NET_ADMIN"]
