apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mosquito
  name: mosquito
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  tolerations:
    - key: "spray"
      operator: "Equal"
      value: "mortein"
      effect: "NoSchedule"