apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    name: static-busybox
spec:
  containers:
  - name: static-busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - sleep
    - "3600"
