apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      name: webserver-pod
      labels:
        app: front-end
    spec:
      containers:
        - name: nginxc
          image: nginx
  replicas: 4