apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
spec:
  selector:
    matchLabels:
      name: busybox-pod
  replicas: 4
  template:
    metadata:
      name: busybox
      labels:
        name: busybox-pod
    spec:
      containers:
        - name: busyboxc
          image: busybox
          command: ["sh", "-c", "while true; do echo 'Hello Kubernetes'; sleep 10; done"]
          