apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: ubuntu-sleeper
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - "sleep"
      - "15"
